from pathlib import Path
import time
import joblib
import pandas as pd
import streamlit as st

from src.run_local_demo import (
    load_artifacts,
    validate_bundle,
    generate_hybrid_recommendations_for_user,
    save_demo_log,
)

from src.feedback_logger import (
    save_feedback_event,
    summarize_feedback_logs,
)


# =========================
# Paths
# =========================

PROJECT_ROOT = Path(__file__).resolve().parent
RETRAINING_DIR = PROJECT_ROOT / "outputs" / "retraining"


# =========================
# Page configuration
# =========================

st.set_page_config(
    page_title="Local Recommender Demo",
    page_icon="🛒",
    layout="centered"
)


# =========================
# Model loading helpers
# =========================

@st.cache_resource
def load_base_model_once():
    """
    Load the original final model artifacts from model_artifacts/.
    This is the base model before retraining.
    """
    hybrid_bundle, user_encoder, item_encoder = load_artifacts()
    validate_bundle(hybrid_bundle)
    return hybrid_bundle, user_encoder, item_encoder


def get_latest_candidate_dir():
    """
    Find the latest retrained candidate model folder inside outputs/retraining/.
    """
    if not RETRAINING_DIR.exists():
        return None

    candidate_dirs = [
        path for path in RETRAINING_DIR.iterdir()
        if path.is_dir() and path.name.startswith("candidate_hybrid_als_content_v2")
    ]

    if not candidate_dirs:
        return None

    latest_dir = max(candidate_dirs, key=lambda path: path.stat().st_mtime)
    return latest_dir


@st.cache_resource
def load_candidate_model_once(candidate_dir_str):
    """
    Load a retrained candidate model from outputs/retraining/.
    """
    candidate_dir = Path(candidate_dir_str)

    hybrid_bundle_path = candidate_dir / "hybrid_model_bundle.pkl"
    user_encoder_path = candidate_dir / "user_encoder.pkl"
    item_encoder_path = candidate_dir / "item_encoder.pkl"

    if not hybrid_bundle_path.exists():
        raise FileNotFoundError(f"Missing file: {hybrid_bundle_path}")

    if not user_encoder_path.exists():
        raise FileNotFoundError(f"Missing file: {user_encoder_path}")

    if not item_encoder_path.exists():
        raise FileNotFoundError(f"Missing file: {item_encoder_path}")

    hybrid_bundle = joblib.load(hybrid_bundle_path)
    user_encoder = joblib.load(user_encoder_path)
    item_encoder = joblib.load(item_encoder_path)

    validate_bundle(hybrid_bundle)

    return hybrid_bundle, user_encoder, item_encoder


def reset_last_result_if_model_changed(active_model_version):
    """
    Clear the previous recommendation result if the user switches model versions.
    This prevents submitting feedback for a result generated by another model.
    """
    previous_model_version = st.session_state.get("active_model_version")

    if previous_model_version is not None and previous_model_version != active_model_version:
        st.session_state.pop("last_recommendation_result", None)
        st.session_state.pop("last_top_k", None)
        st.session_state.pop("last_latency_ms", None)
        st.session_state.pop("last_result_model_version", None)

    st.session_state["active_model_version"] = active_model_version


# =========================
# Main UI
# =========================

st.title("Local Recommender System Demo")

st.write(
    "This local demo loads the saved recommender model artifacts and generates "
    "recommendations without using an API."
)

st.info(
    "For known users, the system uses the Hybrid ALS + Content-Based model. "
    "For new users, it uses the popularity fallback strategy."
)


try:
    # =========================
    # Select model version
    # =========================

    st.subheader("Select Model Version")

    latest_candidate_dir = get_latest_candidate_dir()

    model_options = ["Base final model v1"]

    if latest_candidate_dir is not None:
        model_options.append("Latest retrained candidate model")

    selected_model_version = st.selectbox(
        "Choose model version",
        options=model_options,
        help=(
            "Choose the base model to test the original version. "
            "Choose the latest candidate model to test users added after retraining."
        )
    )

    if selected_model_version == "Base final model v1":
        hybrid_bundle, user_encoder, item_encoder = load_base_model_once()
        active_model_version = "final_hybrid_als_content_v1"
        st.success("Base final model v1 loaded successfully.")

    else:
        hybrid_bundle, user_encoder, item_encoder = load_candidate_model_once(
            str(latest_candidate_dir)
        )
        active_model_version = latest_candidate_dir.name
        st.success(
            f"Latest retrained candidate model loaded successfully: `{active_model_version}`"
        )

    reset_last_result_if_model_changed(active_model_version)

    st.write(f"**Active model version:** `{active_model_version}`")

    st.divider()

    # =========================
    # Model information
    # =========================

    st.subheader("Model Information")

    col1, col2 = st.columns(2)

    with col1:
        st.metric("Model Name", hybrid_bundle["model_name"])
        st.metric("Model Type", hybrid_bundle["model_type"])

    with col2:
        st.metric("ALS Weight", hybrid_bundle["hybrid_params"]["als_weight"])
        st.metric("Content Weight", hybrid_bundle["hybrid_params"]["content_weight"])

    st.divider()

    # =========================
    # Recommendation input
    # =========================

    st.subheader("Generate Recommendations")

    sample_known_user = str(user_encoder.classes_[0])

    visitorid = st.text_input(
        "Enter visitor ID",
        value=sample_known_user,
        help=(
            "Enter an existing visitor ID for personalized recommendations. "
            "Enter a new ID, such as 999999999, to test cold-start fallback. "
            "To test the retrained candidate model, try visitor ID 55."
        )
    )

    top_k = st.slider(
        "Number of recommendations",
        min_value=5,
        max_value=20,
        value=10,
        step=5
    )

    # =========================
    # Generate recommendations
    # =========================

    if st.button("Get Recommendations"):
        start_time = time.perf_counter()

        result = generate_hybrid_recommendations_for_user(
            visitorid=visitorid,
            hybrid_bundle=hybrid_bundle,
            user_encoder=user_encoder,
            item_encoder=item_encoder,
            k=top_k
        )

        latency_ms = (time.perf_counter() - start_time) * 1000

        save_demo_log(result, latency_ms, top_k)

        # Save result in Streamlit session state so feedback can be submitted later.
        st.session_state["last_recommendation_result"] = result
        st.session_state["last_top_k"] = top_k
        st.session_state["last_latency_ms"] = latency_ms
        st.session_state["last_result_model_version"] = active_model_version

    # =========================
    # Show recommendation result
    # =========================

    if "last_recommendation_result" in st.session_state:
        result = st.session_state["last_recommendation_result"]
        top_k = st.session_state["last_top_k"]
        latency_ms = st.session_state["last_latency_ms"]
        result_model_version = st.session_state["last_result_model_version"]

        st.divider()
        st.subheader("Recommendation Result")

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric("Visitor ID", str(result["visitorid"]))

        with col2:
            st.metric("Status", result["status"])

        with col3:
            st.metric("Latency", f"{latency_ms:.2f} ms")

        st.write(f"**Strategy:** `{result['strategy']}`")
        st.write(f"**Top K:** `{top_k}`")
        st.write(f"**Seen items count:** `{result.get('seen_items_count', 0)}`")
        st.write(f"**Result generated by model:** `{result_model_version}`")

        recommendations_df = pd.DataFrame({
            "Rank": list(range(1, len(result["recommendations_itemid"]) + 1)),
            "Recommended Item ID": result["recommendations_itemid"]
        })

        st.dataframe(
            recommendations_df,
            use_container_width=True,
            hide_index=True
        )

        if result["status"] == "cold_start_user":
            st.info(
                "This user is treated as cold-start by the selected model. "
                "The system used the popularity fallback strategy."
            )
        else:
            st.success(
                "This user is known by the selected model. "
                "The system used the Hybrid ALS + Content-Based recommendation strategy."
            )

        # =========================
        # Feedback logging section
        # =========================

        st.divider()
        st.subheader("Submit Feedback")

        st.write(
            "Select one recommended item and the interaction type. "
            "This feedback will be saved locally and can later be used by the retraining pipeline."
        )

        recommended_items = result["recommendations_itemid"]

        selected_item = st.selectbox(
            "Select an item you interacted with",
            options=recommended_items,
            help="Choose one item from the recommendation list."
        )

        feedback_event = st.selectbox(
            "Select feedback event",
            options=["view", "addtocart", "transaction"],
            help="Choose the user action after seeing the recommendation."
        )

        if st.button("Submit Feedback"):
            selected_rank = recommended_items.index(selected_item) + 1

            saved_record = save_feedback_event(
                visitorid=result["visitorid"],
                itemid=selected_item,
                event=feedback_event,
                model_version=result_model_version,
                strategy=result["strategy"],
                recommendation_rank=selected_rank,
                source="streamlit_local_demo",
            )

            st.success("Feedback saved successfully.")
            st.json(saved_record)

    # =========================
    # Feedback summary section
    # =========================

    st.divider()
    st.subheader("Feedback Log Summary")

    feedback_summary = summarize_feedback_logs()

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Feedback Events", feedback_summary["total_feedback_events"])

    with col2:
        st.metric("Unique Users", feedback_summary["unique_users"])

    with col3:
        st.metric("Unique Items", feedback_summary["unique_items"])

    st.write("**Event distribution:**")
    st.json(feedback_summary["event_distribution"])

    st.write(f"**Total feedback weight:** `{feedback_summary['total_feedback_weight']}`")

    if feedback_summary["ready_for_retraining"]:
        st.success("Enough feedback collected for a retraining test.")
    else:
        st.info("Collect more feedback before running retraining.")


except Exception as error:
    st.error("Something went wrong while loading the model or generating recommendations.")
    st.exception(error)